### ISSUE TITLE
Extract links by filter

### ISSUE THREAD

**Issue by cvelele** [az0/linkgopher#18]
Help please,
I try to filter multiple extension like this:

jpg, JPG, bmp, BMP or jpg,JPG,bmp,BMP and any other variation with no luck

Is it possible to filter various extension and how?
Thanks

**Comment by az0** [comment]
The filter is a regular expression

1. Go to this [link demonstration site](https://katana.oooninja.com/link_gopher/link_test.html)
2. Click the Link Gopher icon
3. Click Extract Links by Filter
4. Use this filter: `\.(jpg|JPG|jpeg|JPEG|bmp|BMP|png|PNG)`
