### ISSUE TITLE
pale moon compatibility

### ISSUE THREAD

**Issue by xiconet** [az0/linkgopher#3]
I find your extension to be the most useful in its category. Unfortunately, it's not installable "as is" in Pale Moon. Do you have plans to "fix" this?

**Comment by az0** [comment]
Hmm, could you provide a patch?

**Comment by xiconet** [comment]
I'd be happy to, but I currently have very little idea of how to do this. Maybe in a few weeks or months...

**Comment by az0** [comment]
from the Pale Moon FAQ
https://www.palemoon.org/faq.shtml#Why_do_some_add-ons_not_work
> pale Moon also allows Firefox extensions to be installed, as long as these extensions are compatible 
>with version 24 of Firefox (since that is the closest matching version from an add-on perspective). 

Link Gopher 1.3.3 is requires FF 29+, while Link Gopher 1.3.2 requires FF 2-17.  

Please try Link Gopher 1.3.2 and re-open if this is still an issue.
Old versions: https://addons.mozilla.org/en-us/firefox/addon/link-gopher/versions/

**Comment by xiconet** [comment]
Yes, I already tried that. Unfortunately, my Pale Moon version is 25.3.1 and it doesn't let me install any of the available Link Gopher versions.
