### ISSUE TITLE
Japanese translation of "Link Gopher version 2.0.1"

### ISSUE THREAD

**Issue by Shitennouji** [az0/linkgopher#35]
> linkgopher/_locales/日本語/messages.json
> locales: 日本語（ja-JP）

{
  "askPattern": {
    "message": "リンク内で検索する文字列を入力して下さい。この文字列が無いリンクは無視されます。",
    "description": "none"
  },

  "pleaseWait": {
    "message": "お待ち下さい...",
    "description": "none"
  },

  "links": {
    "message": "リンク先",
    "description": "none"
  },

  "domains": {
    "message": "ドメイン",
    "description": "none"
  },

  "noMatches": {
    "message": "一致するものはありません。",
    "description": "none"
  },

  "extractAll": {
    "message": "すべてのリンクを抽出する",
    "description": "none"
  },

  "extractSome": {
    "message": "フィルタによるリンクの抽出",
    "description": "none"
  },

  "aboutLinkGopher": {
    "message": "Link Gopher について",
    "description": "none"
  }
}

**Comment by az0** [comment]
@Shitennouji 
Thank you for this translation and for your patience. In the future please consider a pull request, which is easier to merge.
