### ISSUE TITLE
Pale Moon 25.3.1 won't allow any of the available Link Gopher versions.

### ISSUE THREAD

**Issue by xiconet** [az0/linkgopher#4]
Sadly, Pale Moon 25.3.1 (which definitely runs much better than Firefox on my "old" machine) won't allow any of the currently available Link Gopher versions.
Not sure, but this might be due to this "GUID" change made by Pale Moon's developer, see https://forum.palemoon.org/viewtopic.php?f=24&t=5932

**Comment by az0** [comment]
I submitted the new Link Gopher extension rewritten for WebExtensions (for modern versions of Firefox) to addons.mozilla.org as a beta release, and it's pending Mozilla's review

**Comment by xiconet** [comment]
Great news, thanks a lot

**Comment by az0** [comment]
Please try Link Gopher Version [2.0beta1](https://addons.mozilla.org/en-US/firefox/addon/link-gopher/versions/beta), and please reply here whether it fixes this issue

**Comment by az0** [comment]
[Link Gopher 2.0](https://addons.mozilla.org/en-US/firefox/addon/link-gopher/) was published. It is a total rewrite from Link Gopher version 1. If you still notice issues, please open a new ticket
