### ISSUE TITLE
linkgopher not work on Chromium-based browsers

### ISSUE THREAD

**Issue by firman000** [az0/linkgopher#45]
hi today the link gopher not working on my chrome and brave, even though yesterday was fine

**Comment by az0** [comment]
This weekend I published Link Gopher version 2.2 which had an error. Just now I published 2.4, and when Google approves it, it should automatically update and work.

**Comment by az0** [comment]
In case you want to side load it, the file is here https://a.tmp.ninja/ZcCoWHjr.zip . (It mangles the filename, but it should be `link-gopher-2.4.zip`.)

**Comment by roweger** [comment]
I have version 2.4 installed on Chromium and Opera and it doesn't seem to work. Clicking any of the buttons does nothing.

**Comment by az0** [comment]
Thanks for the report. I reverted a new feature (keyboard shortcuts for Firefox) and published it on Chrome Web Store as 2.4.2.

**Comment by firman000** [comment]
thank you, the extension is running again

**Comment by az0** [comment]
Thank you for confirming, firman000

**Comment by Sherman-Liu** [comment]
The plugin's not working properly on Firefox 91.0.2 (x64), no response from clicking on any buttons, I tried installing the plugin from the latest GitHub master tree zip, still not working.

**Comment by az0** [comment]
> The plugin's not working properly on Firefox 91.0.2 (x64), no response from clicking on any buttons, I tried installing the plugin from the latest GitHub master tree zip, still not working. @az0

This ticket is for a different issue on Chromium-based browsers (I just updated the title to clarify), but you are using Firefox. Please see https://github.com/az0/linkgopher/issues/48
