### ISSUE TITLE
Fast extraction of links from a multiple web-pages

### ISSUE THREAD

**Issue by Kristinita** [az0/linkgopher#5]
I think that will be very good, if it was possible to enter at once many links to web pages, and Link Gopher extract all links from these web pages.

![Multiple inks](https://i.gyazo.com/149074f1aa075f5979e16c18ff40911f.png)

Thanks.

**Comment by az0** [comment]
That would be interesting, but soon I will not have time to work on this. Feel free to submit a pull request.
