### ISSUE TITLE
Show Domain List Only

### ISSUE THREAD

**Issue by tonydi499** [az0/linkgopher#53]
Using LinkGopher to find hidden spam links on web pages.  Often times the list returned by LinkGopher is quite long requiring scrolling to get to the domain list.  Is there a way to only display the domain name list?  Not a programmer but if it's simply modifying one of the files then I can probably handle that.  😁

**Comment by tonydi499** [comment]
That's great, thanks!  I'm not familiar with how this all works.  Does this mean it will show up in a future update on Mozilla Add Ons  or is there a "beta" version already posted that I can't seem to find?

**Comment by oksim14** [comment]
Hello, it depends :) If author of this extension, @az0 merge this pull request to extension core. If not, you can still download it from github and install it manually (https://github.com/oksim14/linkgopher), its pretty simple:

https://www.mattcutts.com/blog/how-to-install-a-chrome-extension-from-github/

**Comment by tonydi499** [comment]
Simple if you know how all this stuff works.  😁   So here's my **guess** at what I need to do.....download the full package from here, then download your additional code that's in the locales, browser and popup folders.  Unpack the ZIP then substitute those four folders for the ones in the original code.  Then install the whole thing manually (I'm on Firefox, BTW, but I think the same basic process works there too).   Am I close or hopelessly out to lunch?

**Comment by tonydi499** [comment]
Well, maybe out to lunch since I can't seem to figure out how to download

**Comment by tonydi499** [comment]
Ok, I **finally** figured out how to get an XPI copy with the new code. 

Unfortunately, I'm using Firefox not Chrome and Mozilla has removed the options (and eliminated the workarounds) that used to be in place to manually install an extension that isn't signed.

So I guess at this point I'm stuck until @az0 releases an update to the Mozilla Add-Ons site.  ☹️

**Comment by oksim14** [comment]
Hello, I developed it on firefox, so it works :)

First download my repo: https://github.com/oksim14/linkgopher/archive/refs/heads/master.zip

You can try it in developer mode: Settings -> Extensions & Themes -> gear wheel in the top -> Debug addons -> Load temporary Add-on -> select manifest.json from my downloaded and extracted repository

**Comment by tonydi499** [comment]
When I do that I get an error....This add-on could not be installed because it appears to be corrupt.  I tried multiple downloads, same error.

**Comment by az0** [comment]
I merged the change and published it as version 2.5.0. After Google and Mozilla review the changes, it will go live for users.
