### ISSUE TITLE
Link Gopher is now a "legacy" addon for firefox

### ISSUE THREAD

**Issue by rayman3003** [az0/linkgopher#6]
Recently firefox changed its policy for addons. So after the upcoming version 57.0 of firefox, Some addons with "legacy" tags, will not work with firefox anymore.

And "Link Gopher" is now tagged as legacy.

https://support.mozilla.org/en-US/kb/firefox-add-technology-modernizing?as=u&utm_source=inproduct

Could u please update its code to get it compatible with firefox again?

**Comment by az0** [comment]
Thanks for the note. I have the code update, and I need to publish it

**Comment by rayman3003** [comment]
Thank u very much. "Link Gopher" is very important for me. Ill waiting for your update.

**Comment by az0** [comment]
I submitted the new extension rewritten for WebExtensions (for modern versions of Firefox) to addons.mozilla.org as a beta release, and it's pending Mozilla's review

**Comment by rayman3003** [comment]
Thank u very much for your hard work.
--------------------------------------------
On Thu, 11/9/17, Andrew Ziem <notifications@github.com> wrote:

 Subject: Re: [az0/linkgopher] Link Gopher is now a "legacy" addon for firefox (#6)
 To: "az0/linkgopher" <linkgopher@noreply.github.com>
 Cc: "rayman3003" <medal2007a@yahoo.com>, "Author" <author@noreply.github.com>
 Date: Thursday, November 9, 2017, 7:30 AM
 
 I submitted the new extension
 rewritten for WebExtensions (for modern versions of Firefox)
 to addons.mozilla.org as a beta release, and it's
 pending Mozilla's review
 
 —
 You are receiving this because you authored the thread.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by az0** [comment]
Please try Link Gopher Version [2.0beta1](https://addons.mozilla.org/en-US/firefox/addon/link-gopher/versions/beta), and please reply here whether it fixes this issue

**Comment by rayman3003** [comment]
Thank u. I just installed Version 2.0beta1; And so far, it works without any issue. If I found any issue in the future, I would report it to u.
--------------------------------------------
On Tue, 11/14/17, Andrew Ziem <notifications@github.com> wrote:

 Subject: Re: [az0/linkgopher] Link Gopher is now a "legacy" addon for firefox (#6)
 To: "az0/linkgopher" <linkgopher@noreply.github.com>
 Cc: "rayman3003" <medal2007a@yahoo.com>, "Author" <author@noreply.github.com>
 Date: Tuesday, November 14, 2017, 8:27 AM
 
 Please try Link Gopher Version 2.0beta1,
 and please reply here whether it fixes this issue
 
 —
 You are receiving this because you authored the thread.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by az0** [comment]
OK.

[Link Gopher 2.0](https://addons.mozilla.org/en-US/firefox/addon/link-gopher/) was published and approved by Mozilla, so I am closing this ticket.

By the way, 2.0 and 2.0beta1 are mostly identical
