### ISSUE TITLE
Update to Manifest V3

### ISSUE THREAD

**Issue by BilalAslim** [az0/linkgopher#60]
Chrome Web Store will no longer allow Manifest V2 items to be published and was planned to be deprecated in 2023

**Comment by BilalAslim** [comment]
I have the fix for this ready, but I dont have permission to make a branch/pull request

**Comment by az0** [comment]
Can you do PRs for other repositories? Other users have submitted PRs to
this repository without me granting them any special permissions ahead of
time.

**Comment by BilalAslim** [comment]
@az0 nevermind I got it working now, my bad. Just opened the PR. Thanks
