### ISSUE TITLE
Links on website/readme.md to extension.

### ISSUE THREAD

**Issue by shinji257** [az0/linkgopher#63]
For Chrome it links to the publish-accepted link which doesn't actually let you download. (both website and readme.md)
Correct Link: https://chrome.google.com/webstore/detail/link-gopher/bpjdkodgnbfalgghnbeggfbfjpcfamkf

For Firefox it seems to proxy via google redirect.  I don't know if that is intended or not.  (website only)
Correct link is in the readme.md already.

**Comment by az0** [comment]
@shinji257 
Fixed. Thank  you
