### ISSUE TITLE
Please see the issue for Link Gopher - as shown in the screenshot.

### ISSUE THREAD

**Issue by garymgordon** [az0/linkgopher#64]
![link-gopher-display-issue-2023-09-07](https://github.com/az0/linkgopher/assets/3751391/645a1144-1771-4d4e-9194-ab99cf7b63e9)

Please see the issue for Link Gopher - as shown in the screenshot.

This started showing up about a week or more ago.

If this is a bug, please assist in correcting it.
Thanks,
Gary Gordon

**Comment by Mehmuod** [comment]
I too am facing the same problem.
Microsoft Edge: Version 116.0.1938.69 (Official build) (64-bit)
Brave Beta: [Version 1.58.109 Chromium: 116.0.5845.163 (Official Build) beta (64-bit)]

**Comment by Labryn** [comment]
It's a Style issue. I did a quick patch. Just needs to be merged.

#65

**Comment by az0** [comment]
Thank you, I will take a look

**Comment by az0** [comment]
Thank you, I will take a look

**Comment by az0** [comment]
I published the extension, and it's awaiting approval for the extension store
