### ISSUE TITLE
White page

### ISSUE THREAD

**Issue by mnonclerc** [az0/linkgopher#7]
Good evening.

I am a recent user of Link Gopher and have previously enjoyed the quick link retrieval from any given page.  However, as of late, I click of the option to Extract All Links.  It produces a new tab in Firefox with nothing in the Windows.  I followed the thread regarding e10s and have made sure that option was disabled in my about:config.  I also tried uninstalling and re-installing, to no avail.  Currently using 1.3.3.1.  Is there something more I should be looking at?

**Comment by az0** [comment]
I am guessing it has to do with a Firefox upgrade and that Link Gopher 1.3.3.1 uses the outdated XUL system, so today I made progress on publishing Link gopher 2.0beta1.  The code is ready, but I am checking on Mozilla's process. I'll let you know when it has been published.

**Comment by mnonclerc** [comment]
Thank you for your reply. I anxiously await notification.

**Comment by az0** [comment]
I submitted the new extension rewritten for WebExtensions (for modern versions of Firefox) to addons.mozilla.org as a beta release, and it's pending Mozilla's review

**Comment by az0** [comment]
Please try Link Gopher Version [2.0beta1](https://addons.mozilla.org/en-US/firefox/addon/link-gopher/versions/beta), and please reply here whether it fixes this issue

**Comment by az0** [comment]
[Link Gopher 2.0](https://addons.mozilla.org/en-US/firefox/addon/link-gopher/) was published. It is a total rewrite from Link Gopher version 1. If you still notice issues, please open a new ticket
