### ISSUE TITLE
The new version 2.6.1 added empty lines!

### ISSUE THREAD

**Issue by rayman3003** [az0/linkgopher#72]
Since the new version (2.6.1), there is an empty (white) line between each link.

But the previous version(s) doesn't have this empty lines.

Could u please remove these empty lines between each links, So we could copy all links flawlessly?

![2023-10-13 00_36_28-Window](https://github.com/az0/linkgopher/assets/17022701/87786e58-0ba4-4f05-b44d-7f2f9a403e3c)

**Comment by az0** [comment]
On Mozilla, I disabled Link Gopher version 2.6.1, which makes version 2.5.0 the primary version. I assume it will not automatically downgrade you, so you may need to reinstall. Let me know how it goes.

**Comment by rayman3003** [comment]
> On Mozilla, I disabled Link Gopher version 2.6.1, which makes version 2.5.0 the primary version. I assume it will not automatically downgrade you, so you may need to reinstall. Let me know how it goes.

OK. thank u . Downgrading works. 😄

But if there will be a new version in the future, please do not include white spaces.

**Comment by az0** [comment]
> But if there will be a new version in the future, please do not include empty lines.

Sure, makes sense
